name: React CI

on:
  push:
    branches:
      - Restaurant
  pull_request:
    branches:
      - Restaurant

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        env:
          NODE_ENV: production # Ensure this is explicitly set
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/

  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/nizar/Projects/vite-template/  # Path to your application on the server
            git fetch
            git reset --hard origin/Restaurant  # Forcefully pull the latest changes
